[versions]
#jetbrains
kotlin = "1.9.10"
kotlin-immutable-collections = "0.3.6"
#KSP
kotlinxSerializationJson = "1.5.1"
ksp = "1.9.10-1.0.13"
#Androidx
androidx-customView = "1.2.0-alpha02"
androidx-customViewPooling = "1.0.0"
androidx-lifecycle = "2.7.0-alpha02"
androidx-constraintlayout = "2.1.4"
androidx-documentfile = "1.0.1"
androidx-biometricKtx = "1.2.0-alpha05"
androidx-exifinterface = "1.3.6"
androidx-coreKtx = "1.12.0"
androidx-appcompat = "1.6.1"
androidx-swiperefreshlayout = "1.1.0"
#Material
material = "1.10.0"
#patternLockView
patternLockView = "a90b0d4bf0"
#reprint
reprint = "2cb206415d"
#recyclerviewFastscroller
recyclerviewFastscroller = "5a95285b1f"
#rtlViewpager
rtlViewpager = "940f12724f"
#Compose
composeActivity = "1.8.0"
compose = "1.6.0-alpha07"
composeCompiler = "1.5.3"
composeMaterial3 = "1.2.0-alpha09"
#Glide
glide = "4.16.0"
glideCompose = "1.0.0-beta01"
#Room
room = "2.6.0-rc01"
#ezVcard
ezVcard = "0.11.3"
#gson
gson = "2.10.1"
#jodaTime
jodaTime = "2.12.5"
#Gradle
gradlePlugins-agp = "8.1.2"
#build
app-build-compileSDKVersion = "34"
app-build-targetSDK = "34"
app-build-minimumSDK = "23"
app-build-javaVersion = "VERSION_17"
app-build-kotlinJVMTarget = "17"
#versioning
app-version-appId = "com.simplemobiletools.commons"
app-version-groupId = "com.simplemobiletools.commons"
app-version-versionCode = "1"
app-version-versionName = "5.34.26"
[libraries]
#Android X
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-biometric-ktx = { module = "androidx.biometric:biometric-ktx", version.ref = "androidx-biometricKtx" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-coreKtx" }
androidx-customView = { module = "androidx.customview:customview", version.ref = "androidx-customView" }
androidx-customViewPooling = { module = "androidx.customview:customview-poolingcontainer", version.ref = "androidx-customViewPooling" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "androidx-documentfile" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exifinterface" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
#Android X lifecycle
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewModel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
#Room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
#Compose
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
compose-material2 = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-uiTooling-debug = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-uiTooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-view-binding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose" }
#Glide
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compose = { module = "com.github.bumptech.glide:compose", version.ref = "glideCompose" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
#Material
material = { module = "com.google.android.material:material", version.ref = "material" }
#Helpers
patternLockView = { module = "com.github.aritraroy:patternLockView", version.ref = "patternLockView" }
reprint = { module = "com.github.tibbi:reprint", version.ref = "reprint" }
recyclerView-FastScroller = { module = "com.github.tibbi:RecyclerView-FastScroller", version.ref = "recyclerviewFastscroller" }
rtl-viewpager = { module = "com.github.duolingo:rtl-viewpager", version.ref = "rtlViewpager" }
ez-vcard = { module = "com.googlecode.ez-vcard:ez-vcard", version.ref = "ezVcard" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
joda-time = { module = "joda-time:joda-time", version.ref = "jodaTime" }
#Kotlin
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlin-immutable-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-immutable-collections" }
[bundles]
compose = [
    "compose-activity",
    "compose-animation",
    "compose-compiler",
    "compose-foundation",
    "compose-material-icons",
    "compose-material3",
    "compose-runtime",
    "compose-ui",
    "compose-uiTooling-preview",
]
compose-preview = [
    "androidx-customView",
    "androidx-customViewPooling",
    "compose-uiTooling-debug",
]
room = [
    "androidx-room-ktx",
    "androidx-room-runtime",
]
lifecycle = [
    "androidx-lifecycle-compose",
    "androidx-lifecycle-runtime",
    "androidx-lifecycle-viewModel",
    "androidx-lifecycle-viewModel-compose",
]
[plugins]
android = { id = "com.android.application", version.ref = "gradlePlugins-agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
library = { id = "com.android.library", version.ref = "gradlePlugins-agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
